spring:
  application:
    name: diet

  datasource:
    url: jdbc:mysql://zero-spending-db.c7iwog84a8ue.us-east-1.rds.amazonaws.com:3306/0_spending
    username: admin
    password: wlcnf123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

  # AWS S3
  cloud:
    aws:
      s3:
        bucket: 0spending
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}


server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace